//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePOSPrintingService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yqvCU6H7jCxODH8z49Lq1DgjjsUjy+CGLHCPbk5dc2ans4lapfIy7YC/1k7slsjwEep3Ba9dKaGyMDB5c" +
            "2xe5tC9Anp2K/s8azqJiPMytqghMI2swRsRHvrfbqmmWsfg/FSnHdrXacyQwtwJEsZTJyDbzsZhVnfLp" +
            "g+rmpIPEvR9KP9/h9Viwke488+Qdb9z")]
        public string DBConnection {
            get {
                return ((string)(this["DBConnection"]));
            }
            set {
                this["DBConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\deleteme\\")]
        public string FileWatcherPath {
            get {
                return ((string)(this["FileWatcherPath"]));
            }
            set {
                this["FileWatcherPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"PageWidth\":1.5,\"PageHeight\":1,\"MarginTop\":0,\"MarginRight\":0,\"MarginBottom\":0,\"M" +
            "arginLeft\":0}")]
        public string LabelPageSetup {
            get {
                return ((string)(this["LabelPageSetup"]));
            }
            set {
                this["LabelPageSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OneNote")]
        public string LabelPrinterName {
            get {
                return ((string)(this["LabelPrinterName"]));
            }
            set {
                this["LabelPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
    {
        ""ReceiptName"": ""Invoice En"",
        ""ReceiptFileName"": ""rpt_receipt_en"",
        ""InvoiceFileName"": ""rpt_invoice_en"",
        ""number_invoice_copies"": 1,
        ""number_receipt_copies"": 2,
        ""PageWidth"": 2.85,
        ""PageHeight"": 11,
        ""MarginTop"": 0,
        ""MarginRight"": 0,
        ""MarginBottom"": 0,
        ""MarginLeft"": 0
    },
    {
        ""ReceiptName"": ""Invoice Kh"",
        ""ReceiptFileName"": ""rpt_receipt_kh"",
        ""InvoiceFileName"": ""rpt_inoice_kh"",
        ""number_invoice_copies"": 2,
        ""number_receipt_copies"": 1,
        ""PageWidth"": 2.85,
        ""PageHeight"": 11,
        ""MarginTop"": 0,
        ""MarginRight"": 0,
        ""MarginBottom"": 0,
        ""MarginLeft"": 0
    },
    {
        ""ReceiptName"": ""Kitchen Order"",
        ""ReceiptFileName"": ""rpt_kitchen_order"",
        ""InvoiceFileName"": ""rpt_kitchen_order"",
        ""number_invoice_copies"": 1,
        ""number_receipt_copies"": 1,
        ""PageWidth"": 2.85,
        ""PageHeight"": 11,
        ""MarginTop"": 0,
        ""MarginRight"": 0,
        ""MarginBottom"": 0,
        ""MarginLeft"": 0
    }
]")]
        public string ReceiptSettings {
            get {
                return ((string)(this["ReceiptSettings"]));
            }
            set {
                this["ReceiptSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cashier Printer")]
        public string CashierPrinter {
            get {
                return ((string)(this["CashierPrinter"]));
            }
            set {
                this["CashierPrinter"] = value;
            }
        }
    }
}
