//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePOSPrintingService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\ESTC\\ePOS\\watcher\\")]
        public string FileWatcherPath {
            get {
                return ((string)(this["FileWatcherPath"]));
            }
            set {
                this["FileWatcherPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Label Printer")]
        public string LabelPrinterName {
            get {
                return ((string)(this["LabelPrinterName"]));
            }
            set {
                this["LabelPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n\t{\r\n\t\t\"ReceiptName\":\"Invoice En\",\r\n\t\t\"ReceiptFileName\":\"rpt_receipt_en\",\r\n\t\t\"I" +
            "nvoiceFileName\":\"rpt_invoice_en\",\r\n\t\t\"number_invoice_copies\":1,\r\n\t\t\"number_recei" +
            "pt_copies\":1,\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"Mar" +
            "ginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"I" +
            "nvoice Kh\",\r\n\t\t\"ReceiptFileName\":\"rpt_receipt_kh\",\r\n\t\t\"InvoiceFileName\":\"rpt_inv" +
            "oice_kh\",\r\n\t\t\"number_invoice_copies\":1,\r\n\t\t\"number_receipt_copies\":1,\r\n\t\t\"PageWi" +
            "dth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginB" +
            "ottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n{\r\n\t\t\"ReceiptName\":\"Label\",\r\n\t\t\"ReceiptFileNam" +
            "e\":\"rpt_label\",\r\n\t\t\"InvoiceFileName\":\"rpt_label\",\r\n\t\t\"PageWidth\":1.57,\r\n\t\t\"PageH" +
            "eight\":1,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginL" +
            "eft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Kitchen Order\",\r\n\t\t\"ReceiptFileName\":\"rpt_kitc" +
            "hen_order\",\r\n\t\t\"InvoiceFileName\":\"rpt_kitchen_order\",\r\n\t\t\"number_invoice_copies\"" +
            ":1,\r\n\t\t\"number_receipt_copies\":1,\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"M" +
            "arginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{" +
            "\r\n\t\t\"ReceiptName\":\"Kitchen Message\",\r\n\t\t\"ReceiptFileName\":\"rpt_kitchen_message\"," +
            "\r\n\t\t\"InvoiceFileName\":\"rpt_kitchen_message\",\r\n\t\t\"number_invoice_copies\":1,\r\n\t\t\"n" +
            "umber_receipt_copies\":1,\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\"" +
            ":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"Rece" +
            "iptName\":\"Close Working Day\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_working_day_summar" +
            "y\",\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":" +
            "0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Close Worki" +
            "ng Day Sale Product\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_working_day_sale_product\"," +
            "\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r" +
            "\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Close Working " +
            "Day Sale Transaction\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_working_day_sale_transact" +
            "ion\",\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight" +
            "\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Close Cas" +
            "hier Shift Summary\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_cashier_shift_summary\",\r\n\t\t" +
            "\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"" +
            "MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Close Cashier Shif" +
            "t Sale Transaction\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_cashier_shift_sale_transact" +
            "ion\",\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight" +
            "\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Close Cas" +
            "hier Shift Sale Product\",\r\n\t\t\"ReceiptFileName\":\"rpt_close_cashier_shift_sale_pro" +
            "duct\",\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRigh" +
            "t\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Deleted " +
            "Sale Order\",\r\n\t\t\"InvoiceFileName\":\"rpt_deleted_invoice\",\r\n\t\t\"PageWidth\":2.85,\r\n\t" +
            "\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t" +
            "\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Park Item Receipt\",\r\n\t\t\"ReceiptFileNam" +
            "e\":\"rpt_park_item_receipt\",\r\n\t\t\"number_receipt_copies\":1,\r\n\t\t\"PageWidth\":2.85,\r\n" +
            "\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t" +
            "\t\"MarginLeft\":0\r\n\t},\r\n\t{\r\n\t\t\"ReceiptName\":\"Waiting Order\",\r\n\t\t\"InvoiceFileName\":" +
            "\"rpt_waiting_order\",\r\n\t\t\"PageWidth\":2.85,\r\n\t\t\"PageHeight\":11,\r\n\t\t\"MarginTop\":0,\r" +
            "\n\t\t\"MarginRight\":0,\r\n\t\t\"MarginBottom\":0,\r\n\t\t\"MarginLeft\":0\r\n\t}\r\n]")]
        public string ReceiptSettings {
            get {
                return ((string)(this["ReceiptSettings"]));
            }
            set {
                this["ReceiptSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cashier Printer")]
        public string CashierPrinter {
            get {
                return ((string)(this["CashierPrinter"]));
            }
            set {
                this["CashierPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.10.13:9697/restaurant_client_api/api/")]
        public string BaseAPIURL {
            get {
                return ((string)(this["BaseAPIURL"]));
            }
            set {
                this["BaseAPIURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"is_usb\":false,\"port\":\"COM1\"}")]
        public string USBCashDrawer {
            get {
                return ((string)(this["USBCashDrawer"]));
            }
            set {
                this["USBCashDrawer"] = value;
            }
        }
    }
}
